# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e33319a59587a67db2a74244696b6a320e253f19fe7d7055e58f881983296d2891be1d5400352d8e068d1c6a37d8cf444a70ca83c9faf8fef724bce9e7caba4

test:
  secret_key_base: b63337f044bc3f61de670b93eb664e1d6add042d11174337b6b8f21257208f284aea4c4ab132c18863375a2300e0ec0b69c768270491a38af755fd4cf086384c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
